# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  depoly:
    runs-on: centos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Flask app
      uses: actions/setup-python@v2
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        
        script: |
          mkdir test
          cd test
          git clone git@github.com:CodeReber/jimthedevopsguy.git
          echo 'Deployment works'
